server:
  port: 8080

zuul:
  routes:
    productService:
      path: /products/**
    pricingService:
      path: /prices/**

eureka:
  client:
    serviceUrl:
      defaultZone:  http://discovery:9000/eureka/

